<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.3.0
 *   protoc               — v6.33.5
 * Source: google/protobuf/compiler/plugin.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Compiler\CodeGeneratorResponse;

/**
 * @api
 *
 * Sync with code_generator.h.
 */
enum Feature: int
{
    case FEATURE_NONE = 0;
    case FEATURE_PROTO3_OPTIONAL = 1;
    case FEATURE_SUPPORTS_EDITIONS = 2;
}
