<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.13
 *   protoc               — v6.33.5
 * Source: google/protobuf/compiler/plugin.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Compiler;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * An encoded CodeGeneratorRequest is written to the plugin's stdin.
 */
final readonly class CodeGeneratorRequest
{
    /**
     * @param list<string> $fileToGenerate The .proto files that were explicitly listed on the command-line.  The
     * code generator should generate code only for these files.  Each file's
     * descriptor will be included in proto_file, below.
     * @param ?string $parameter The generator parameter passed on the command-line.
     * @param list<\Google\Protobuf\FileDescriptorProto> $protoFile FileDescriptorProtos for all files in files_to_generate and everything
     * they import.  The files will appear in topological order, so each file
     * appears before any file that imports it.
     *
     * Note: the files listed in files_to_generate will include runtime-retention
     * options only, but all other files will include source-retention options.
     * The source_file_descriptors field below is available in case you need
     * source-retention options for files_to_generate.
     *
     * protoc guarantees that all proto_files will be written after
     * the fields above, even though this is not technically guaranteed by the
     * protobuf wire format.  This theoretically could allow a plugin to stream
     * in the FileDescriptorProtos and handle them one by one rather than read
     * the entire set into memory at once.  However, as of this writing, this
     * is not similarly optimized on protoc's end -- it will store all fields in
     * memory at once before sending them to the plugin.
     *
     * Type names of fields and extensions in the FileDescriptorProto are always
     * fully qualified.
     * @param list<\Google\Protobuf\FileDescriptorProto> $sourceFileDescriptors File descriptors with all options, including source-retention options.
     * These descriptors are only provided for the files listed in
     * files_to_generate.
     * @param ?\Google\Protobuf\Compiler\Version $compilerVersion The version number of protocol compiler.
     */
    public function __construct(
        #[Reflection\Field(1, new Reflection\ListT(Reflection\StringT::T, false))]
        public array $fileToGenerate = [],
        #[Reflection\Field(2, Reflection\StringT::T)]
        public ?string $parameter = null,
        #[Reflection\Field(15, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FileDescriptorProto::class), false))]
        public array $protoFile = [],
        #[Reflection\Field(17, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\FileDescriptorProto::class), false))]
        public array $sourceFileDescriptors = [],
        #[Reflection\Field(3, new Reflection\ObjectT(\Google\Protobuf\Compiler\Version::class))]
        public ?\Google\Protobuf\Compiler\Version $compilerVersion = null,
    ) {}
}
