<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.2
 *   protoc               — v6.32.1
 * Source: google/protobuf/compiler/plugin.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Compiler;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The plugin writes an encoded CodeGeneratorResponse to stdout.
 */
final readonly class CodeGeneratorResponse
{
    /**
     * @param ?string $error Error message.  If non-empty, code generation failed.  The plugin process
     * should exit with status code zero even if it reports an error in this way.
     *
     * This should be used to indicate errors in .proto files which prevent the
     * code generator from generating correct code.  Errors which indicate a
     * problem in protoc itself -- such as the input CodeGeneratorRequest being
     * unparseable -- should be reported by writing a message to stderr and
     * exiting with a non-zero status code.
     * @param ?\BcMath\Number $supportedFeatures A bitmask of supported features that the code generator supports.
     * This is a bitwise "or" of values from the Feature enum.
     * @param ?int $minimumEdition The minimum edition this plugin supports.  This will be treated as an
     * Edition enum, but we want to allow unknown values.  It should be specified
     * according the edition enum value, *not* the edition number.  Only takes
     * effect for plugins that have FEATURE_SUPPORTS_EDITIONS set.
     * @param ?int $maximumEdition The maximum edition this plugin supports.  This will be treated as an
     * Edition enum, but we want to allow unknown values.  It should be specified
     * according the edition enum value, *not* the edition number.  Only takes
     * effect for plugins that have FEATURE_SUPPORTS_EDITIONS set.
     * @param list<\Google\Protobuf\Compiler\CodeGeneratorResponse\File> $file
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\StringT::T)]
        public ?string $error = null,
        #[Reflection\Field(2, Reflection\Uint64T::T)]
        public ?\BcMath\Number $supportedFeatures = null,
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public ?int $minimumEdition = null,
        #[Reflection\Field(4, Reflection\Int32T::T)]
        public ?int $maximumEdition = null,
        #[Reflection\Field(15, new Reflection\ListT(new Reflection\ObjectT(\Google\Protobuf\Compiler\CodeGeneratorResponse\File::class), false))]
        public array $file = [],
    ) {}
}
