<?php

/**
 * Code generated by thesis/protoc-plugin. DO NOT EDIT.
 * Versions:
 *   thesis/protoc-plugin — v0.1.23
 *   protoc               — v6.33.5
 * Source: google/protobuf/compiler/plugin.proto
 */

declare(strict_types=1);

namespace Google\Protobuf\Compiler;

use Thesis\Protobuf\Reflection;

/**
 * @api
 *
 * The version number of protocol compiler.
 */
final readonly class Version
{
    /**
     * @param ?string $suffix A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
     * be empty for mainline stable releases.
     */
    public function __construct(
        #[Reflection\Field(1, Reflection\Int32T::T)]
        public ?int $major = null,
        #[Reflection\Field(2, Reflection\Int32T::T)]
        public ?int $minor = null,
        #[Reflection\Field(3, Reflection\Int32T::T)]
        public ?int $patch = null,
        #[Reflection\Field(4, Reflection\StringT::T)]
        public ?string $suffix = null,
    ) {}
}
